apiVersion: v1
kind: Service
metadata:
  name: flask-mongodb-app-service
spec:
  selector:
    app: flask-mongodb-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30007 # A port within the range 30000-32767
  type: NodePort
