apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-mongodb-app-deployment
  labels:
    app: flask-mongodb-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-mongodb-app
  template:
    metadata:
      labels:
        app: flask-mongodb-app
    spec:
      containers:
      - name: flask-mongodb-app
        image: mlogesh/flask-mongodb-app:1.0 # Update with your image
        ports:
        - containerPort: 5000
        env:
        - name: MONGODB_URI
          value: "mongodb://admin:password123@mongodb.default.svc.cluster.local:27017/?authSource=admin"
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
